version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: ./kafka_deploy
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 0.0.0.0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spring-backend:
    build: .
    container_name: spring-backend
    ports:
      - "8080:8080"
  angularclient:
    build: frontend/angularclient/.
    container_name: angularclient
    ports:
      - "4200:80"
    links:
      - spring-backend