name: experiencing-kafka CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache Maven dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Check Coding Style
        working-directory: ./backend
        run: mvn checkstyle:check

  build_Test_CodeCoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Cache Maven dependencies
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build
        working-directory: ./backend
        run: mvn package -DskipTests

      - name: Tests
        working-directory: ./backend
        run: mvn test
        
      - name: Generate_Code_Coverage_report
        working-directory: ./backend
        run: mvn jacoco:report
